include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
  errors:
    missing_required_param: error
    import_of_legacy_library_into_null_safe: ignore
    deprecated_member_use: ignore
    avoid_function_literals_in_foreach_calls: ignore
    depend_on_referenced_packages: ignore
    no_leading_underscores_for_local_identifiers: ignore
    use_key_in_widget_constructors: ignore
    avoid_renaming_method_parameters: ignore
    use_build_context_synchronously: ignore
    sort_child_properties_last: ignore
    prefer_typing_uninitialized_variables: ignore
    no_logic_in_create_state: ignore
    unrelated_type_equality_checks: ignore
    avoid_types_as_parameter_names: ignore
    overridden_fields: ignore
    void_checks: ignore
    unnecessary_getters_setters: ignore
    constant_identifier_names: ignore
    non_constant_identifier_names: ignore


linter:
  rules:
    - avoid_print
    - prefer_is_empty
    - prefer_is_not_empty
    - avoid_init_to_null
    - prefer_conditional_assignment
    - prefer_if_null_operators
    - unnecessary_null_in_if_null_operators
    - avoid_unnecessary_containers
    - avoid_web_libraries_in_flutter
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - sized_box_for_whitespace
    - curly_braces_in_flow_control_structures
    - cancel_subscriptions