name: example_lint
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  analyzer: ^5.2.0
  analyzer_plugin: ^0.11.2
  custom_lint_builder: ^0.3.4

dev_dependencies:
  test: ^1.16.0